Script started on Wed 07 Nov 2018 01:22:28 PM EST
[?1034hbash-4.2$ sys161 kernel "p testbin/add 89 67;q"
sys161: System/161 release 2.0.2, compiled Feb  2 2015 11:24:13

OS/161 base system version 2.0
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

Aakarshika Priydarshi's system version 0 (ASST4b #26)

5896k physical memory available
Prcoess Bootstrap successfulDevice probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
OS/161 kernel: p testbin/add 89 67
Answer: 156
Operation took 0.109256381 seconds
OS/161 kernel: q
Shutting down.
The system is halted.
sys161: 36609293 cycles (35625715 run, 983578 global-idle)
sys161:   cpu0: 7528595 kern, 2276 user, 0 idle; 9452 ll, 9452/0 sc, 36348 sync
sys161: 1365 irqs 52 exns 0r/0w disk 0r/695w console 9r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 0.314861 seconds (116.271 mhz)
sys161: Elapsed virtual time: 1.468661444 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Wed 07 Nov 2018 01:23:01 PM EST
