Script started on Wed 07 Nov 2018 12:39:09 PM EST
[?1034hbash-4.2$ exitsys161 kernel "p testbin/badcall;q"[C[C[C[C[C[C[C[C[C[C[21Pcd os161/root/
bash-4.2$ cd os161/root/[C[C[C[C[C[C[C[C[C[Cexit[Ksys161 kernel "p testbin/badcall;q"
sys161: System/161 release 2.0.2, compiled Feb  2 2015 11:24:13

OS/161 base system version 2.0
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

Aakarshika Priydarshi's system version 0 (ASST4b #26)

5896k physical memory available
Prcoess Bootstrap successfulDevice probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
OS/161 kernel: p testbin/badcall
[a-|, 1-4, *, ?=menu, !=quit]
[a] execv                   [b] waitpid                 
[c] open                    [d] read                    
[e] write                   [f] close                   
[g] reboot                  [h] sbrk                    
[i] ioctl                   [j] lseek                   
[k] fsync                   [l] ftruncate               
[m] fstat                   [n] remove                  
[o] rename                  [p] link                    
[q] mkdir                   [r] rmdir                   
[s] chdir                   [t] getdirentry             
[u] symlink                 [v] readlink                
[w] dup2                    [x] pipe                    
[y] __time                  [z] __getcwd                
[{] stat                    [|] lstat                   
[1] asst1                   [2] asst2                   
[3] asst3                   [4] asst4                   
[*] all                     [!] quit                    
Choose: a
testbin/badcall: passed: exec NULL
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec invalid pointer
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec kernel pointer
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec the empty string
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec /bin/true with NULL arglist
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec /bin/true with invalid pointer arglist
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec /bin/true with kernel pointer arglist
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec /bin/true with invalid pointer arg
testbin/badcall: FAILURE: wrong exit code of subprocess
testbin/badcall: passed: exec /bin/true with kernel pointer arg
testbin/badcall: FAILURE: wrong exit code of subprocess
Choose: !
Operation took 30.255083926 seconds
OS/161 kernel: q
Shutting down.
The system is halted.
sys161: 790217462 cycles (222375766 run, 567841696 global-idle)
sys161:   cpu0: 145633885 kern, 133801 user, 0 idle; 55777 ll, 55777/0 sc, 144406 sync
sys161: 5485 irqs 6292 exns 0r/0w disk 2r/2739w console 10r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 28.534950 seconds (27.693 mhz)
sys161: Elapsed virtual time: 31.612988669 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Wed 07 Nov 2018 12:40:03 PM EST
