Script started on Wed 07 Nov 2018 12:42:42 PM EST
[?1034hbash-4.2$ exitsys161 kernel "p testbin/multiexec;q"[C[C[C[C[C[C[C[C[C[C[23Pcd os161/root/
bash-4.2$ cd os161/root/[C[C[C[C[C[C[C[C[C[Cexit[Ksys161 kernel "p testbin/multiexec;q"[1P;q"[1P;q"[1P;q"[1P;q"[1P;q"[1P;q"[1P;q"[1P;q"[1P;q"f;q"o;q"r;q"k;q"t;q"e;q"s;q"t;q"
sys161: System/161 release 2.0.2, compiled Feb  2 2015 11:24:13

OS/161 base system version 2.0
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

Aakarshika Priydarshi's system version 0 (ASST4b #26)

5896k physical memory available
Prcoess Bootstrap successfulDevice probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
OS/161 kernel: p testbin/forktest
testbin/forktest: Starting. Expect this many:
|----------------------------|
001111222222223333333333333333
testbin/forktest: Complete.
Operation took 1.672853611 seconds
OS/161 kernel: q
Shutting down.
The system is halted.
sys161: 75664340 cycles (74676768 run, 987572 global-idle)
sys161:   cpu0: 42763800 kern, 437374 user, 0 idle; 13214 ll, 13214/0 sc, 44823 sync
sys161: 1729 irqs 24643 exns 0r/0w disk 0r/821w console 9r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 1.716951 seconds (44.069 mhz)
sys161: Elapsed virtual time: 3.030863234 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Wed 07 Nov 2018 12:42:55 PM EST
