Script started on Wed 07 Nov 2018 01:25:36 PM EST
[?1034hbash-4.2$ sys161 kernel "p testbin/muli[Ktiexec;q"
sys161: System/161 release 2.0.2, compiled Feb  2 2015 11:24:13

OS/161 base system version 2.0
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

Aakarshika Priydarshi's system version 0 (ASST4b #26)

5896k physical memory available
Prcoess Bootstrap successfulDevice probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
OS/161 kernel: p testbin/multiexec
Forking 12 child processes...
Waiting for fork...
Starting the execs...
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
emu0:
Succeeded
Unknown syscall 68
Unknown syscall 68
Operation took 2.751348901 seconds
OS/161 kernel: q
Shutting down.
The system is halted.
sys161: 102024278 cycles (101025788 run, 998490 global-idle)
sys161:   cpu0: 70088896 kern, 13919 user, 0 idle; 19327 ll, 19327/0 sc, 58871 sync
sys161: 2049 irqs 992 exns 0r/0w disk 0r/890w console 117r/0w/27m emufs 0r/0w net
sys161: Elapsed real time: 2.811774 seconds (36.2847 mhz)
sys161: Elapsed virtual time: 4.085260844 seconds (25 mhz)
bash-4.2$ exit
exit

Script done on Wed 07 Nov 2018 01:26:12 PM EST
